#pragma once

extern const char* PNG_SelectorScreenBGCenter;
extern const char* JPG_SelectorScreenBGCenter;
extern const char* PNG_SelectorScreenBGLeft;
extern const char* JPG_SelectorScreenBGLeft;
extern const char* PNG_SelectorScreenBGRight;
extern const char* JPG_SelectorScreenBGRight;
extern const char* background1;
extern const char* background1unsodded;
extern const char* background2;
extern const char* AwardScreen_Back;
extern const char* IMG_sod1row;
extern const char* IMG_sod1row_;
extern const char* IMG_seeds;
extern const char* IMG_SeedPacketSilhouette;
extern const char* IMG_seedBank;
extern const char* IMG_FlagMeter;
extern const char* IMG_FlagMeterParts;
extern const char* IMG_ConveyorBelt;
extern const char* IMG_ConveyorBelt_backdrop;
extern const char* IMG_Wallnut_cracked1;
extern const char* IMG_Wallnut_cracked2;
extern const char* IMG_SeedChooser_Button;
extern const char* IMG_Zombie_cone2;
extern const char* IMG_Zombie_cone3;
extern const char* IMG_Zombie_bucket2;
extern const char* IMG_Zombie_bucket3;
extern const char* IMG_Pea_splats;