name: test-clang-format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.18.1
      with:
        source: '.'
        extensions: 'hpp,cpp'
        clangFormatVersion: 18
        style: file
